export const REQUEST_LINKS = 'REQUEST_LINKS'
export const REQUEST_LINKS_SUCCESS = 'REQUEST_LINKS_SUCCESS'

export const POST_LINK = 'POST_LINK'
export const POST_LINK_SUCCESS = 'POST_LINK_SUCCESS'

export const UPDATE_LINK = 'UPDATE_LINK'
export const UPDATE_LINK_SUCCESS = 'UPDATE_LINK_SUCCESS'

export const DELETE_LINK = 'DELETE_LINK'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
