export const REQUEST_SOCIAL = 'REQUEST_SOCIAL'
export const REQUEST_SOCIAL_SUCCESS = 'REQUEST_SOCIAL_SUCCESS'

export const UPDATE_SOCIAL = 'UPDATE_SOCIAL'
export const UPDATE_SOCIAL_SUCCESS = 'UPDATE_SOCIAL_SUCCESS'
