export const REQUEST_CAROUSEL_LIST = 'REQUEST_CAROUSEL_LIST'
export const REQUEST_CAROUSEL_LIST_SUCCESS = 'REQUEST_CAROUSEL_LIST_SUCCESS'

export const POST_CAROUSEL = 'POST_CAROUSEL'
export const POST_CAROUSEL_SUCCESS = 'POST_CAROUSEL_SUCCESS'

export const UPDATE_CAROUSEL = 'UPDATE_CAROUSEL'
export const UPDATE_CAROUSEL_SUCCESS = 'UPDATE_CAROUSEL_SUCCESS'

export const DELETE_CAROUSEL = 'DELETE_CAROUSEL'
export const DELETE_CAROUSEL_SUCCESS = 'DELETE_CAROUSEL_SUCCESS'
