export const REQUEST_CAROUSEL_LIST = 'REQUEST_CAROUSEL_LIST'
export const REQUEST_CAROUSEL_LIST_SUCCESS = 'REQUEST_CAROUSEL_LIST_SUCCESS'

export const POST_CAROUSEL = 'REQUEST_CAROUSEL_LIST'
export const POST_CAROUSEL_COMPLETED = 'REQUEST_CAROUSEL_LIST_COMPLETED'
export const POST_CAROUSEL_WARNING = 'REQUEST_CAROUSEL_LIST_WARNING'
export const POST_CAROUSEL_FAILED = 'REQUEST_CAROUSEL_LIST_FAILED'
export const POST_CAROUSEL_FATAL = 'REQUEST_CAROUSEL_LIST_FATAL'
export const RESET_POST_ERROR = 'RESET_ERROR'
