export const REQUEST_WRITERS = 'REQUEST_WRITERS'
export const REQUEST_WRITERS_SUCCESS = 'REQUEST_WRITERS_SUCCESS'

export const POST_WRITER = 'POST_WRITER'
export const POST_WRITER_SUCCESS = 'POST_WRITER_SUCCESS'

export const UPDATE_WRITER = 'UPDATE_WRITER'
export const UPDATE_WRITER_SUCCESS = 'UPDATE_WRITER_SUCCESS'

export const DELETE_WRITER = 'DELETE_WRITER'
export const DELETE_WRITER_SUCCESS = 'DELETE_WRITER_SUCCESS'
