export const REQUEST_CONTACT_LIST = 'REQUEST_CONTACT_LIST'
export const REQUEST_CONTACT_LIST_SUCCESS = 'REQUEST_CONTACT_LIST_SUCCESS'

export const POST_CONTACT = 'POST_CONTACT'
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
